#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${package}.view;

import ${package}.pojo.${project-name-uppercase}Pojo;
import ${package}.service.${project-name-uppercase}Service;
import ${package}.ui.BaseWindow;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 * @author lgdamy on 25/01/2021
 */
public class ${project-name-uppercase}Panel implements BaseWindow.ContentForm {
    private JTextField numberField;
    private JButton gerarButton;
    private JPanel root;
    private JRadioButton imparRadio;
    private JRadioButton parRadio;
    private JRadioButton primeRadio;

    public ${project-name-uppercase}Panel() {
        gerarButton.addActionListener(this::gerar);
    }

    private void gerar(ActionEvent e) {
        ${project-name-uppercase}Pojo pojo = ${project-name-uppercase}Service.getInstance().gerarNumeroAleatorio();
        numberField.setText(pojo.getRandomNumber() + "");
        parRadio.setSelected(pojo.isEven());
        imparRadio.setSelected(pojo.isOdd());
        primeRadio.setSelected(pojo.isPrime());
    }

    @Override
    public JPanel root() {
        return this.root;
    }

//    Sobrescreva esse metodo apenas se sua janela vai mudar de titulo
//    @Override
//    public String title() {
//        return "Meu titulo especial";
//    }
    
//    Codigo gerado pelo .form Intellij, descomente ele caso voce esteja usando outra/nenhuma IDE
//    {
//// GUI initializer generated by IntelliJ IDEA GUI Designer
//// >>> IMPORTANT!! <<<
//// DO NOT EDIT OR ADD ANY CODE HERE!
//        $$$setupUI$$$();
//    }
//
//    /**
//     * Method generated by IntelliJ IDEA GUI Designer
//     * >>> IMPORTANT!! <<<
//     * DO NOT edit this method OR call it in your code!
//     *
//     * @noinspection ALL
//     */
//    private void $$$setupUI$$$() {
//        root = new JPanel();
//        root.setLayout(new GridBagLayout());
//        final JLabel label1 = new JLabel();
//        label1.setText("Número:");
//        GridBagConstraints gbc;
//        gbc = new GridBagConstraints();
//        gbc.gridx = 1;
//        gbc.gridy = 0;
//        gbc.anchor = GridBagConstraints.WEST;
//        root.add(label1, gbc);
//        numberField = new JTextField();
//        numberField.setText("0");
//        gbc = new GridBagConstraints();
//        gbc.gridx = 3;
//        gbc.gridy = 0;
//        gbc.weightx = 1.0;
//        gbc.anchor = GridBagConstraints.WEST;
//        gbc.fill = GridBagConstraints.HORIZONTAL;
//        root.add(numberField, gbc);
//        gerarButton = new JButton();
//        gerarButton.setText("Gerar");
//        gbc = new GridBagConstraints();
//        gbc.gridx = 5;
//        gbc.gridy = 0;
//        root.add(gerarButton, gbc);
//        final JPanel spacer1 = new JPanel();
//        gbc = new GridBagConstraints();
//        gbc.gridx = 4;
//        gbc.gridy = 0;
//        gbc.fill = GridBagConstraints.HORIZONTAL;
//        root.add(spacer1, gbc);
//        final JPanel spacer2 = new JPanel();
//        gbc = new GridBagConstraints();
//        gbc.gridx = 2;
//        gbc.gridy = 0;
//        gbc.fill = GridBagConstraints.HORIZONTAL;
//        root.add(spacer2, gbc);
//        final JPanel spacer3 = new JPanel();
//        gbc = new GridBagConstraints();
//        gbc.gridx = 0;
//        gbc.gridy = 0;
//        gbc.fill = GridBagConstraints.HORIZONTAL;
//        root.add(spacer3, gbc);
//        final JPanel spacer4 = new JPanel();
//        gbc = new GridBagConstraints();
//        gbc.gridx = 6;
//        gbc.gridy = 0;
//        gbc.fill = GridBagConstraints.HORIZONTAL;
//        root.add(spacer4, gbc);
//        final JPanel panel1 = new JPanel();
//        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
//        gbc = new GridBagConstraints();
//        gbc.gridx = 3;
//        gbc.gridy = 1;
//        gbc.fill = GridBagConstraints.BOTH;
//        root.add(panel1, gbc);
//        imparRadio = new JRadioButton();
//        imparRadio.setText("Impar");
//        panel1.add(imparRadio);
//        parRadio = new JRadioButton();
//        parRadio.setText("Par");
//        panel1.add(parRadio);
//        primeRadio = new JRadioButton();
//        primeRadio.setText("Primo");
//        panel1.add(primeRadio);
//    }
//
//    /**
//     * @noinspection ALL
//     */
//    public JComponent $$$getRootComponent$$$() {
//        return root;
//    }
}
